# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

# Stack: <name>
# Description: <what this stack does>

services:
  example:
    container_name: example
    image: example/image:latest
    restart: unless-stopped
    # depends_on:
    #   - other-service
    # ports:
    #   - "8080:80"
    volumes:
      - /mnt/user/appdata/example:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    environment:
      TZ: "America/Chicago"
    # command:
    #   - "--arg=value"
    # labels:
    #   traefik.enable: true
    #   traefik.http.routers.example.rule: "Host(`example.trkm.io`)"
    #   traefik.http.services.example.loadBalancer.server.port: 8080

networks:
  proxy:
    external: true
