---
# Role metadata and dependencies

dependencies:
  - role: trkm.main.packages
    vars:
      update_cache: true
      update_packages: false
      packages: "{{ common_packages }}"
      remove_packages: "{{ common_remove_packages }}"
