---
# Default variables for docker role

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_remove_packages_apt:
  - docker.io
  - docker-doc
  - docker-compose
  - docker-compose-v2
  - podman-docker
  - containerd
  - runc

docker_remove_packages_dnf:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-engine
  - docker-engine-selinux
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-selinux
  - podman
  - runc

docker_packages_pacman:
  - docker
  - docker-compose

docker_service_enabled: true
docker_service_state: started
