# Headscale configuration
# Docs: https://headscale.net/ref/configuration/

server_url: https://hs.trkm.io

listen_addr: 0.0.0.0:8080
grpc_listen_addr: 0.0.0.0:50443
grpc_allow_insecure: false

private_key_path: /var/lib/headscale/private.key
noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
  allocation: sequential

database:
  type: sqlite
  sqlite:
    path: /var/lib/headscale/db.sqlite

ephemeral_node_inactivity_timeout: 30m

derp:
  server:
    enabled: false
    region_id: 999
    region_code: "local"
    region_name: "Local DERP"
    stun_listen_addr: "0.0.0.0:3478"
    private_key_path: /var/lib/headscale/derp_server_private.key
    automatically_add_embedded_derp_region: false
    ipv4: ""
    ipv6: ""
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  auto_update_enabled: true
  update_frequency: 24h

tls_cert_path: ""
tls_key_path: ""

dns:
  nameservers:
    global:
      - 1.1.1.1
      - 1.0.0.1
  magic_dns: true
  base_domain: ts.trkm.io

unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"

log:
  format: text
  level: info

policy:
  path: /etc/headscale/acl.json
  mode: file
