services:
  flaresolverr:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/flaresolverr.png'
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: 'bash'