# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - /mnt/user/appdata/sonarr/hd/config:/config
      - /mnt/user/data:/data
    networks:
      - pvr
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"

  sonarr_4k:
    container_name: sonarr_4k
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - "8990:8989"
    volumes:
      - /mnt/user/appdata/sonarr/4k/config:/config
      - /mnt/user/data:/data
    networks:
      - pvr
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"

  sonarr_anime:
    container_name: sonarr_anime
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - "8991:8989"
    volumes:
      - /mnt/user/appdata/sonarr/anime/config:/config
      - /mnt/user/data:/data
    networks:
      - pvr
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"

networks:
  pvr:
    external: true
