---
all:
  vars:
    timezone: "America/Chicago"
  children:
    swarm:
      children:
        swarm_managers:
          hosts:
            trkm-dock-01:
        swarm_workers:
          hosts:
            trkm-dock-02:
            trkm-dock-03:
