# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  kometa:
    container_name: kometa
    image: kometateam/kometa:latest
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/kometa/config:/config
    networks:
      - pvr
    environment:
      TZ: "America/Chicago"
      KOMETA_TIMES: "${KOMETA_TIMES}"
      KOMETA_PLEXURL: "${PLEX_URL}"
      KOMETA_PLEXTOKEN: "${PLEX_TOKEN}"
      KOMETA_TMDBKEY: "${TMDB_APIKEY}"
      KOMETA_MDBKEY: "${MDB_APIKEY}"
      KOMETA_RADARRURL: "${RADARR_URL}"
      KOMETA_RADARRAPIKEY: "${RADARR_APIKEY}"
      KOMETA_SONARRURL: "${SONARR_URL}"
      KOMETA_SONARRAPIKEY: "${SONARR_APIKEY}"

networks:
  pvr:
    external: true
