# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - /mnt/user/appdata/radarr/hd/config:/config
      - /mnt/user/data:/data
    networks:
      - pvr
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/radarr.png"
      net.unraid.docker.webui: "http://[IP]:[PORT:7878]"
      net.unraid.docker.shell: "bash"

  radarr_4k:
    container_name: radarr_4k
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - "7879:7878"
    volumes:
      - /mnt/user/appdata/radarr/4k/config:/config
      - /mnt/user/data:/data
    networks:
      - pvr
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/radarr-4k.png"
      net.unraid.docker.webui: "http://[IP]:[PORT:7879]"
      net.unraid.docker.shell: "bash"

  radarr_anime:
    container_name: radarr_anime
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - "7880:7878"
    volumes:
      - /mnt/user/appdata/radarr/anime/config:/config
      - /mnt/user/data:/data
    networks:
      - pvr
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/radarr.png"
      net.unraid.docker.webui: "http://[IP]:[PORT:7880]"
      net.unraid.docker.shell: "bash"

networks:
  pvr:
    external: true
