# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  app:
    image: portainer/portainer-ce:2.33
    volumes:
      - /mnt/nas/trkm-unraid/appdata/portainer/data:/data
    networks:
      - net
      - proxy
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.trkm.io`)"
        - "traefik.http.services.portainer.loadBalancer.server.port=9443"
        - "traefik.http.services.portainer.loadBalancer.server.scheme=https"

  agent:
    image: portainer/agent:2.33
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
    networks:
      - net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  net:
    driver: overlay
  proxy:
    driver: overlay
    external: true
