# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/sabnzbd/config:/config
      - /mnt/user/data/usenet:/data/usenet
    network_mode: container:gluetun
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/sabnzbd.png"
      net.unraid.docker.webui: "http://[IP]:[PORT:8080]"
      net.unraid.docker.shell: "bash"
