services:
  sabnzbd:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/sabnzbd.png'
      net.unraid.docker.webui: 'http://[IP]:[PORT:8080]'
      net.unraid.docker.shell: 'bash'