# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/qbittorrent/config:/config
      - /mnt/user/data/torrents:/data/torrents
    networks:
      - pvr
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
      WEBUI_PORT: "8081"
      TORRENTING_PORT: "6881"

networks:
  pvr:
    external: true
