services:
  qbittorrent:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/qbittorrent.png'
      net.unraid.docker.webui: 'http://[IP]:[PORT:8081]'
      net.unraid.docker.shell: 'bash'