services:
  overseerr:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/overseerr.png'
      net.unraid.docker.webui: 'http://[IP]:[PORT:5055]'
      net.unraid.docker.shell: 'bash'