# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: unless-stopped
    ports:
      - "3000:3000"   # Web UI
      - "2222:22"     # SSH
    volumes:
      - /mnt/user/appdata/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: sqlite3
      GITEA__server__ROOT_URL: "https://git.trkm.io"
      GITEA__server__SSH_DOMAIN: "git.trkm.io"
      GITEA__server__SSH_PORT: 2222
      GITEA__server__SSH_LISTEN_PORT: 22
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.gitea.rule: "Host(`git.trkm.io`)"
      traefik.http.services.gitea.loadBalancer.server.port: 3000

networks:
  proxy:
    external: true
