---
collections:
  - name: ansible.posix
    version: ">=1.5.0"

  - name: community.general
    version: ">=8.0.0"

roles:
  - name: geerlingguy.docker
    version: ">=7.0.0"

  - name: geerlingguy.nfs
    version: ">=2.0.0"
