---
# Update playbook - updates package cache and upgrades all packages
- name: Update all servers
  hosts: all
  become: true
  roles:
    - role: trkm.main.packages
      vars:
        update_cache: true
        update_packages: true
