# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  cloudflare_ddns:
    container_name: cloudflare_ddns
    image: favonia/cloudflare-ddns:latest
    restart: unless-stopped
    networks:
      br0:
        ipv4_address: "10.10.20.254"
    environment:
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
      DOMAINS: "trkm.io"
      IP6_PROVIDER: "none"
      PROXIED: "true"
    labels:
      net.unraid.docker.icon: "https://hotio.dev/webhook-avatars/cloudflareddns.png"
      net.unraid.docker.shell: "bash"

networks:
  br0:
    external: true
