# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/recyclarr/config:/config
    networks:
      - pvr
    environment:
      CRON_SCHEDULE: "@daily"
      RECYCLARR_CREATE_CONFIG: "false"
      TZ: "America/Chicago"
    user: "99:100"

networks:
  pvr:
    external: true
